from typing import Any

class SQLiteClient:
    def __init__(self, connect_address: str) -> None: ...
    def execute(self, query: str, *params: object) -> dict[str, Any]: ...
    def __enter__(self) -> "SQLiteClient": ...
    def __exit__(self, exc_type: type[BaseException] | None, exc_value: BaseException | None, traceback: object | None) -> None: ...
